### ISSUE TITLE
Any Interest in adding Chess War features?

### ISSUE THREAD

**Issue by zotz** [andrew-wilkes/godot-chess#2]
I am currently working on adding Chess War features to HexChess from https://github.com/esbudylin/HexChess
My stuff is here as HexChessWar: https://github.com/zotz/HexChessWar

Would you be interested in adding Chess War Features to your godot-chess?

HexChess and thus HexChessWar) has peer to peer network play.
godot-chess has the ability to play against an engine.

I have an old tcl/tk single machine, no engine chess war on sourceforge from years ago:
https://sourceforge.net/projects/zbcw/

I look forward to your response.

**Comment by andrew-wilkes** [comment]
Hello, thanks for your suggestion. I don't have any plans to add extra features to godot-chess at this time.
