### ISSUE TITLE
Can't find path normally in Windows

### ISSUE THREAD

**Issue by Garbage123King** [andrew-wilkes/godot-chess#3]
When press "PLAY", it shows:

>Missing iopiper at:  /bin/iopiper

Then I found "cmd" didn't work well.
```
if OS.get_name() == "Windows":
        print("it is windows")
	cmd = "cd"
	ext = ".exe"
var output = []
var _exit_code = OS.execute(cmd, [], true, output)
print(output)
```

output is:
```
it is windows
[]
```

**Comment by andrew-wilkes** [comment]
Thanks for your input. There seems to be a new way to specify a Windows command which I have implemented in the latest commit. This appears to have fixed the issue.
I tested with Windows 10 and Godot 3.5.2 -stable
