### ISSUE TITLE
I think there is a problem with the Makefile

### ISSUE THREAD

**Issue by zotz** [andrew-wilkes/godot-chess#4]
I am trying to add chess war features to godot-chess.

I may have Level 1 game play mostly working.

What I have so far is here:

https://github.com/zotz/godot-chess-war/tree/zbcw

My thinking on a fix for the Makefile is included there.

If you have a chance, I would appreciate if you could test what I have done and comment on the direction I am taking so far and point out any obvious mistakes or omissions you see.

I think I may adopt an approach I have taken here to my effort to being Chess War to HexChess which I am working on here:

https://github.com/zotz/HexChessWar

In case anyone reading this is interested.

**Comment by andrew-wilkes** [comment]
I don't understand what is your problem with the Make File.

I look forward to seeing what you come up with by adding Chess War features.

**Comment by zotz** [comment]
IIRC,

your Makefile:

`build:
	go build -o bin/ src/engine/sampler.go
	go build -o bin/ src/engine/iopiper.go
	go build -o bin/ src/engine/ping-server.go`

did not make the binaries for me. I had to do this:

`build:
	go build -o bin/sampler src/engine/sampler.go
	go build -o bin/iopiper src/engine/iopiper.go
	go build -o bin/ping-server src/engine/ping-server.go`

I can't get the indents to work properly. Check my zbcw branch.

If you have some time, please run what I have in the zbcw branch and provide a bit of feedback.

**Comment by andrew-wilkes** [comment]
I have cloned the repo and will have a look at the weekend. This Chess project was very challenging for me and now I am a bit rusty on it though.

**Comment by zotz** [comment]
> I have cloned the repo and will have a look at the weekend. This Chess project was very challenging for me and now I am a bit rusty on it though.

If you would like to be in touch via email, send me an email at zlocz@yahoo.com and I will send you my main email address to use.

If you would like a more "interactive interaction" ;-) I can do irc, signal, google chat, and possibly a few others. Let me know.

**Comment by andrew-wilkes** [comment]
OK maybe I will send you an email to keep in touch.

Regarding the Makefile, I didn't need to specify the file name for the executable. The Go compiler seemed to work it out, and also, in Windows it added the .exe extension which Windows requires. But Make is not built into the Windows OS and is a pain to install, so it's easier to directly build the exe file in Windows for folks that are interested.

**Comment by zotz** [comment]
I thought your make file worked for me the first time I looked at your code.

Somewhere I uninstalled. The next time I installed, the make did not work as I tried to explain.

I will try to duplicate my issue while making a screen cap to see if we can figure out what was up.

**Comment by andrew-wilkes** [comment]
I guess it is to do with the versions of Go. I have version 1.15.15 but now it's at version 1.20.3

**Comment by zotz** [comment]
My version on the machine in question:

$ go version
go version go1.10.4 linux/amd64
